/**
 * generated by Xtext 2.13.0
 */
package com.example.ui;

import com.example.ui.AbstractClassesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ClassesUiModule extends AbstractClassesUiModule {
  public ClassesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
