/*
 * generated by Xtext 2.18.0.M3
 */
package com.altran.general.integration.xtextsirius.test.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class EKeyLangUiModule extends AbstractEKeyLangUiModule {
}
