/**
 * generated by Xtext 2.13.0
 */
package com.example.ui.contentassist;

import com.example.ui.contentassist.AbstractClassesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ClassesProposalProvider extends AbstractClassesProposalProvider {
}
