/*
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import nl.altran.example.xtext.html.ui.internal.HtmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class HtmlLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {
	
	@Override
	protected Bundle getBundle() {
		return HtmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HtmlActivator.getInstance().getInjector(HtmlActivator.NL_ALTRAN_EXAMPLE_XTEXT_HTML_HTMLLANG);
	}
	
}
