/**
 * generated by Xtext 2.12.0
 */
package com.example.classes.validation;

import com.example.classes.validation.AbstractInlineeditValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class InlineeditValidator extends AbstractInlineeditValidator {
}
