/**
 * generated by Xtext 2.13.0
 */
package com.example.validation;

import com.example.validation.AbstractClassesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ClassesValidator extends AbstractClassesValidator {
}
