/**
 * generated by Xtext 2.18.0.M3
 */
package com.altran.general.integration.xtextsirius.test.ide;

import com.altran.general.integration.xtextsirius.test.EKeyLangRuntimeModule;
import com.altran.general.integration.xtextsirius.test.EKeyLangStandaloneSetup;
import com.altran.general.integration.xtextsirius.test.ide.EKeyLangIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EKeyLangIdeSetup extends EKeyLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    EKeyLangRuntimeModule _eKeyLangRuntimeModule = new EKeyLangRuntimeModule();
    EKeyLangIdeModule _eKeyLangIdeModule = new EKeyLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_eKeyLangRuntimeModule, _eKeyLangIdeModule));
  }
}
