/**
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.htmlLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc --> A representation of the model object '
 * <em><b>Body Contents</b></em>'. <!-- end-user-doc -->
 *
 *
 * @see nl.altran.example.xtext.html.htmlLang.HtmlLangPackage#getBodyContents()
 * @model
 * @generated
 */
public interface BodyContents extends EObject {
} // BodyContents
