/**
 * generated by Xtext 2.9.1
 */
package nl.altran.example.xtext.html.htmlLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Freeform Text</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.altran.example.xtext.html.htmlLang.HtmlLangPackage#getFreeformText()
 * @model
 * @generated
 */
public interface FreeformText extends TextElement
{
} // FreeformText
