/**
 * generated by Xtext 2.9.1
 */
package nl.altran.example.xtext.html.htmlLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Style</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.altran.example.xtext.html.htmlLang.Style#getStyles <em>Styles</em>}</li>
 * </ul>
 *
 * @see nl.altran.example.xtext.html.htmlLang.HtmlLangPackage#getStyle()
 * @model
 * @generated
 */
public interface Style extends Header
{
  /**
   * Returns the value of the '<em><b>Styles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Styles</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Styles</em>' attribute.
   * @see #setStyles(String)
   * @see nl.altran.example.xtext.html.htmlLang.HtmlLangPackage#getStyle_Styles()
   * @model
   * @generated
   */
  String getStyles();

  /**
   * Sets the value of the '{@link nl.altran.example.xtext.html.htmlLang.Style#getStyles <em>Styles</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Styles</em>' attribute.
   * @see #getStyles()
   * @generated
   */
  void setStyles(String value);

} // Style
