/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.example.fowlerdsl.services.InlineEditGrammarAccess;

public class InlineEditParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private InlineEditGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.example.fowlerdsl.parser.antlr.internal.InternalInlineEditParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.example.fowlerdsl.parser.antlr.internal.InternalInlineEditParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Statemachine";
	}
	
	public InlineEditGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(InlineEditGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
