/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.example.fowlerdsl.services.StatemachineGrammarAccess;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class InlineEditGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class StatemachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.example.fowlerdsl.InlineEdit.Statemachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStatemachineAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cEventsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cEventsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_1_1_0 = (RuleCall)cEventsAssignment_1_1.eContents().get(0);
		private final Keyword cEndKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cResetEventsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cResetEventsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cResetEventsEventCrossReference_2_1_0 = (CrossReference)cResetEventsAssignment_2_1.eContents().get(0);
		private final RuleCall cResetEventsEventIDTerminalRuleCall_2_1_0_1 = (RuleCall)cResetEventsEventCrossReference_2_1_0.eContents().get(1);
		private final Keyword cEndKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommandsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCommandsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCommandsCommandParserRuleCall_3_1_0 = (RuleCall)cCommandsAssignment_3_1.eContents().get(0);
		private final Keyword cEndKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cConstantsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cConstantsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cConstantsConstantParserRuleCall_4_1_0 = (RuleCall)cConstantsAssignment_4_1.eContents().get(0);
		private final Keyword cEndKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Assignment cStatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatesStateParserRuleCall_5_0 = (RuleCall)cStatesAssignment_5.eContents().get(0);
		
		//// We have to repeat the root element, because Xtext uses the first rule as entry rule.
		////@Override 
		//Statemachine:
		//	{Statemachine} ('events'
		//	events+=Event+
		//	'end')? ('resetEvents'
		//	resetEvents+=[Event]+
		//	'end')? ('commands'
		//	commands+=Command+
		//	'end')? ('constants'
		//	constants+=Constant+
		//	'end')?
		//	states+=State*;
		@Override public ParserRule getRule() { return rule; }

		//{Statemachine} ('events' events+=Event+ 'end')? ('resetEvents' resetEvents+=[Event]+ 'end')? ('commands'
		//commands+=Command+ 'end')? ('constants' constants+=Constant+ 'end')? states+=State*
		public Group getGroup() { return cGroup; }

		//{Statemachine}
		public Action getStatemachineAction_0() { return cStatemachineAction_0; }

		//('events' events+=Event+ 'end')?
		public Group getGroup_1() { return cGroup_1; }

		//'events'
		public Keyword getEventsKeyword_1_0() { return cEventsKeyword_1_0; }

		//events+=Event+
		public Assignment getEventsAssignment_1_1() { return cEventsAssignment_1_1; }

		//Event
		public RuleCall getEventsEventParserRuleCall_1_1_0() { return cEventsEventParserRuleCall_1_1_0; }

		//'end'
		public Keyword getEndKeyword_1_2() { return cEndKeyword_1_2; }

		//('resetEvents' resetEvents+=[Event]+ 'end')?
		public Group getGroup_2() { return cGroup_2; }

		//'resetEvents'
		public Keyword getResetEventsKeyword_2_0() { return cResetEventsKeyword_2_0; }

		//resetEvents+=[Event]+
		public Assignment getResetEventsAssignment_2_1() { return cResetEventsAssignment_2_1; }

		//[Event]
		public CrossReference getResetEventsEventCrossReference_2_1_0() { return cResetEventsEventCrossReference_2_1_0; }

		//ID
		public RuleCall getResetEventsEventIDTerminalRuleCall_2_1_0_1() { return cResetEventsEventIDTerminalRuleCall_2_1_0_1; }

		//'end'
		public Keyword getEndKeyword_2_2() { return cEndKeyword_2_2; }

		//('commands' commands+=Command+ 'end')?
		public Group getGroup_3() { return cGroup_3; }

		//'commands'
		public Keyword getCommandsKeyword_3_0() { return cCommandsKeyword_3_0; }

		//commands+=Command+
		public Assignment getCommandsAssignment_3_1() { return cCommandsAssignment_3_1; }

		//Command
		public RuleCall getCommandsCommandParserRuleCall_3_1_0() { return cCommandsCommandParserRuleCall_3_1_0; }

		//'end'
		public Keyword getEndKeyword_3_2() { return cEndKeyword_3_2; }

		//('constants' constants+=Constant+ 'end')?
		public Group getGroup_4() { return cGroup_4; }

		//'constants'
		public Keyword getConstantsKeyword_4_0() { return cConstantsKeyword_4_0; }

		//constants+=Constant+
		public Assignment getConstantsAssignment_4_1() { return cConstantsAssignment_4_1; }

		//Constant
		public RuleCall getConstantsConstantParserRuleCall_4_1_0() { return cConstantsConstantParserRuleCall_4_1_0; }

		//'end'
		public Keyword getEndKeyword_4_2() { return cEndKeyword_4_2; }

		//states+=State*
		public Assignment getStatesAssignment_5() { return cStatesAssignment_5; }

		//State
		public RuleCall getStatesStateParserRuleCall_5_0() { return cStatesStateParserRuleCall_5_0; }
	}

	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.xtext.example.fowlerdsl.InlineEdit.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cGuardAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cGuardGuardParserRuleCall_0_1_0 = (RuleCall)cGuardAssignment_0_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cEventAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEventEventCrossReference_1_0 = (CrossReference)cEventAssignment_1.eContents().get(0);
		private final RuleCall cEventEventIDTerminalRuleCall_1_0_1 = (RuleCall)cEventEventCrossReference_1_0.eContents().get(1);
		private final Keyword cEqualsSignGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cStateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cStateStateCrossReference_3_0 = (CrossReference)cStateAssignment_3.eContents().get(0);
		private final RuleCall cStateStateIDTerminalRuleCall_3_0_1 = (RuleCall)cStateStateCrossReference_3_0.eContents().get(1);
		
		////@Override 
		//Transition:
		//	('[' guard=Guard ']')? event=[Event] '=>' state=[State];
		@Override public ParserRule getRule() { return rule; }

		//('[' guard=Guard ']')? event=[Event] '=>' state=[State]
		public Group getGroup() { return cGroup; }

		//('[' guard=Guard ']')?
		public Group getGroup_0() { return cGroup_0; }

		//'['
		public Keyword getLeftSquareBracketKeyword_0_0() { return cLeftSquareBracketKeyword_0_0; }

		//guard=Guard
		public Assignment getGuardAssignment_0_1() { return cGuardAssignment_0_1; }

		//Guard
		public RuleCall getGuardGuardParserRuleCall_0_1_0() { return cGuardGuardParserRuleCall_0_1_0; }

		//']'
		public Keyword getRightSquareBracketKeyword_0_2() { return cRightSquareBracketKeyword_0_2; }

		//event=[Event]
		public Assignment getEventAssignment_1() { return cEventAssignment_1; }

		//[Event]
		public CrossReference getEventEventCrossReference_1_0() { return cEventEventCrossReference_1_0; }

		//ID
		public RuleCall getEventEventIDTerminalRuleCall_1_0_1() { return cEventEventIDTerminalRuleCall_1_0_1; }

		//'=>'
		public Keyword getEqualsSignGreaterThanSignKeyword_2() { return cEqualsSignGreaterThanSignKeyword_2; }

		//state=[State]
		public Assignment getStateAssignment_3() { return cStateAssignment_3; }

		//[State]
		public CrossReference getStateStateCrossReference_3_0() { return cStateStateCrossReference_3_0; }

		//ID
		public RuleCall getStateStateIDTerminalRuleCall_3_0_1() { return cStateStateIDTerminalRuleCall_3_0_1; }
	}
	
	
	private final StatemachineElements pStatemachine;
	private final TransitionElements pTransition;
	
	private final Grammar grammar;

	private final StatemachineGrammarAccess gaStatemachine;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public InlineEditGrammarAccess(GrammarProvider grammarProvider,
		StatemachineGrammarAccess gaStatemachine,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaStatemachine = gaStatemachine;
		this.gaTerminals = gaTerminals;
		this.pStatemachine = new StatemachineElements();
		this.pTransition = new TransitionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.xtext.example.fowlerdsl.InlineEdit".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public StatemachineGrammarAccess getStatemachineGrammarAccess() {
		return gaStatemachine;
	}

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// We have to repeat the root element, because Xtext uses the first rule as entry rule.
	////@Override 
	//Statemachine:
	//	{Statemachine} ('events'
	//	events+=Event+
	//	'end')? ('resetEvents'
	//	resetEvents+=[Event]+
	//	'end')? ('commands'
	//	commands+=Command+
	//	'end')? ('constants'
	//	constants+=Constant+
	//	'end')?
	//	states+=State*;
	public StatemachineElements getStatemachineAccess() {
		return pStatemachine;
	}
	
	public ParserRule getStatemachineRule() {
		return getStatemachineAccess().getRule();
	}

	////@Override 
	//Transition:
	//	('[' guard=Guard ']')? event=[Event] '=>' state=[State];
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}

	//Event:
	//	name=ID code=INT? ('[' guard=Guard ']')?;
	public StatemachineGrammarAccess.EventElements getEventAccess() {
		return gaStatemachine.getEventAccess();
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//Guard:
	//	ValueGuard | RangeGuard;
	public StatemachineGrammarAccess.GuardElements getGuardAccess() {
		return gaStatemachine.getGuardAccess();
	}
	
	public ParserRule getGuardRule() {
		return getGuardAccess().getRule();
	}

	//ValueGuard:
	//	cond=Value;
	public StatemachineGrammarAccess.ValueGuardElements getValueGuardAccess() {
		return gaStatemachine.getValueGuardAccess();
	}
	
	public ParserRule getValueGuardRule() {
		return getValueGuardAccess().getRule();
	}

	//RangeGuard:
	//	min=Value '..' max=Value;
	public StatemachineGrammarAccess.RangeGuardElements getRangeGuardAccess() {
		return gaStatemachine.getRangeGuardAccess();
	}
	
	public ParserRule getRangeGuardRule() {
		return getRangeGuardAccess().getRule();
	}

	//Value:
	//	ConstantRef | IntLiteral;
	public StatemachineGrammarAccess.ValueElements getValueAccess() {
		return gaStatemachine.getValueAccess();
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}

	//ConstantRef:
	//	constant=[Constant];
	public StatemachineGrammarAccess.ConstantRefElements getConstantRefAccess() {
		return gaStatemachine.getConstantRefAccess();
	}
	
	public ParserRule getConstantRefRule() {
		return getConstantRefAccess().getRule();
	}

	//IntLiteral:
	//	value=INT;
	public StatemachineGrammarAccess.IntLiteralElements getIntLiteralAccess() {
		return gaStatemachine.getIntLiteralAccess();
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}

	//Command:
	//	name=ID code=ID;
	public StatemachineGrammarAccess.CommandElements getCommandAccess() {
		return gaStatemachine.getCommandAccess();
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}

	//Constant:
	//	name=ID value=Value;
	public StatemachineGrammarAccess.ConstantElements getConstantAccess() {
		return gaStatemachine.getConstantAccess();
	}
	
	public ParserRule getConstantRule() {
		return getConstantAccess().getRule();
	}

	//State:
	//	'state' name=ID ('description' description=STRING)? ('actions' '{' actions+=[Command]+ '}')?
	//	transitions+=super::Transition* 'end';
	public StatemachineGrammarAccess.StateElements getStateAccess() {
		return gaStatemachine.getStateAccess();
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
