/**
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.ui;

import nl.altran.example.xtext.html.ui.AbstractHtmlLangUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class HtmlLangUiModule extends AbstractHtmlLangUiModule {
  public HtmlLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
