/*
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class HtmlLangUiModule extends AbstractHtmlLangUiModule {
}
