/**
 * generated by Xtext 2.22.0
 */
package com.example.classes.impl;

import com.example.classes.BuiltInType;
import com.example.classes.ClassesPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Built In Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BuiltInTypeImpl extends TypeImpl implements BuiltInType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BuiltInTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ClassesPackage.Literals.BUILT_IN_TYPE;
  }

} //BuiltInTypeImpl
