/*
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.ide


/**
 * Use this class to register ide components.
 */
class HtmlLangIdeModule extends AbstractHtmlLangIdeModule {
}
