/**
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HtmlLangIdeModule extends AbstractHtmlLangIdeModule {
}
