<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="EKeyLang" nsURI="http://altran.com/general/integration/xtextsirius/test/EKeyLang"
    nsPrefix="EKeyLang">
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//ANamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//IContainerContent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IContainerContent" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ANamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//ANamedElement #//IContainerContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafs" upperBound="-1"
        eType="#//Leaf" containment="true" eKeys="#//ANamedElement/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leaf" eSuperTypes="#//ANamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//ANamedElement #//IContainerContent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leaf" eType="#//Leaf" containment="true"
        eKeys="#//ANamedElement/name"/>
  </eClassifiers>
</ecore:EPackage>
