/**
 * generated by Xtext 2.14.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.edit.ide;

import com.altran.general.integration.xtextsirius.test.reflang.edit.RefLangEditRuntimeModule;
import com.altran.general.integration.xtextsirius.test.reflang.edit.RefLangEditStandaloneSetup;
import com.altran.general.integration.xtextsirius.test.reflang.edit.ide.RefLangEditIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RefLangEditIdeSetup extends RefLangEditStandaloneSetup {
  @Override
  public Injector createInjector() {
    RefLangEditRuntimeModule _refLangEditRuntimeModule = new RefLangEditRuntimeModule();
    RefLangEditIdeModule _refLangEditIdeModule = new RefLangEditIdeModule();
    return Guice.createInjector(Modules2.mixin(_refLangEditRuntimeModule, _refLangEditIdeModule));
  }
}
