/**
 * generated by Xtext 2.18.0.M3
 */
package com.example.classes;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.example.classes.ClassModel#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see com.example.classes.ClassesPackage#getClassModel()
 * @model
 * @generated
 */
public interface ClassModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference list.
   * The list contents are of type {@link com.example.classes.Content}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference list.
   * @see com.example.classes.ClassesPackage#getClassModel_Content()
   * @model containment="true"
   * @generated
   */
  EList<Content> getContent();

} // ClassModel
