/**
 * generated by Xtext 2.17.0
 */
package com.example.classes;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.example.classes.ClassesPackage#getIntegerType()
 * @model
 * @generated
 */
public interface IntegerType extends BuiltInType
{
} // IntegerType
