/**
 * generated by Xtext 2.12.0
 */
package com.example.classes;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.example.classes.ClassesPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
