/*
 * generated by Xtext 2.14.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.edit


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RefLangEditStandaloneSetup extends RefLangEditStandaloneSetupGenerated {

	def static void doSetup() {
		new RefLangEditStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
