/**
 * generated by Xtext 2.14.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.ide;

import com.altran.general.integration.xtextsirius.test.reflang.ide.AbstractRefLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RefLangIdeModule extends AbstractRefLangIdeModule {
}
