/**
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.htmlLang.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import nl.altran.example.xtext.html.htmlLang.BodyContents;
import nl.altran.example.xtext.html.htmlLang.HtmlLangPackage;

/**
 * <!-- begin-user-doc --> An implementation of the model object '
 * <em><b>Body Contents</b></em>'. <!-- end-user-doc -->
 *
 * @generated
 */
public class BodyContentsImpl extends MinimalEObjectImpl.Container implements BodyContents {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	protected BodyContentsImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return HtmlLangPackage.Literals.BODY_CONTENTS;
	}

} // BodyContentsImpl
