/**
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.htmlLang.impl;

import org.eclipse.emf.ecore.EClass;

import nl.altran.example.xtext.html.htmlLang.HtmlLangPackage;
import nl.altran.example.xtext.html.htmlLang.Italics;

/**
 * <!-- begin-user-doc --> An implementation of the model object '
 * <em><b>Italics</b></em>'. <!-- end-user-doc -->
 *
 * @generated
 */
public class ItalicsImpl extends TextElementImpl implements Italics {
	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	protected ItalicsImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 *
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return HtmlLangPackage.Literals.ITALICS;
	}

} // ItalicsImpl
