/*
 * generated by Xtext 2.9.1
 */
package nl.altran.example.xtext.html.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HtmlLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/altran/example/xtext/html/parser/antlr/internal/InternalHtmlLang.tokens");
	}
}
