/*
 * generated by Xtext 2.9.1
 */
package nl.altran.example.xtext.html.parser.antlr;

import com.google.inject.Inject;
import nl.altran.example.xtext.html.parser.antlr.internal.InternalHtmlLangParser;
import nl.altran.example.xtext.html.services.HtmlLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HtmlLangParser extends AbstractAntlrParser {

	@Inject
	private HtmlLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	

	@Override
	protected InternalHtmlLangParser createParser(XtextTokenStream stream) {
		return new InternalHtmlLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Html";
	}

	public HtmlLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HtmlLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
