/*
 * generated by Xtext 2.12.0
 */
package nl.altran.example.xtext.html.parser.antlr;

import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import nl.altran.example.xtext.html.parser.antlr.internal.InternalHtmlLangParser;
import nl.altran.example.xtext.html.services.HtmlLangGrammarAccess;

public class HtmlLangParser extends AbstractAntlrParser {
	
	@Inject
	private HtmlLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(final XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}


	@Override
	protected InternalHtmlLangParser createParser(final XtextTokenStream stream) {
		return new InternalHtmlLangParser(stream, getGrammarAccess());
	}

	@Override
	protected String getDefaultRuleName() {
		return "Html";
	}

	public HtmlLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(final HtmlLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
