package com.altran.general.integration.xtextsirius.test.util.modelregioneditorpreparer;

import java.util.Collections;
import java.util.Set;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Command;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Event;
import org.eclipse.xtext.example.fowlerdsl.statemachine.State;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Statemachine;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Transition;
import org.eclipse.xtext.util.TextRegion;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.junit.Assert;
import org.junit.Test;

import com.altran.general.integration.xtextsirius.test.AFowlerdslDefaultModelTest;
import com.altran.general.integration.xtextsirius.util.ModelRegionEditorPreparer;
import com.google.inject.Injector;

@SuppressWarnings("all")
public class TestApiMultiEntries extends AModelRegionEditorPreparer {
	@Test
	public void eventOnlyName() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final Set<String> _emptySet = CollectionLiterals.<String> emptySet();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptySet);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(20, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 2");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2 3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final Set<String> _emptySet = CollectionLiterals.<String> emptySet();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptySet);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2 3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 2", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(22, 8);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCodeGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 1 [pi..1]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 2 [42]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("pi 314");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final Set<String> _emptySet = CollectionLiterals.<String> emptySet();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptySet);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 1 [pi..1]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 2 [42]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("pi 314");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 2 [42]",
				_text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(30, 13);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventOnlyName_name() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(20, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCode_name() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 234");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2 345");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 234");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2 345");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(24, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCode_nameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 234");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2 345");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "code")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 234");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2 345");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 234", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(24, 10);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameGuard_nameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 [pi..1]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 [42]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "code")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 [pi..1]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 [42]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(28, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameGuard_nameGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 [pi..1]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 [42]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 [pi..1]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 [42]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 [42]", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(28, 11);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCodeGuard_nameGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 123 [pi..1]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 234 [42]");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event3 345");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 123 [pi..1]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 234 [42]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event3 345");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 234 [42]",
				_text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(32, 15);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventName_nameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "code")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(20, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventName_nameCodeGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "code", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(20, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventName_guard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event1[");
		_builder_1.newLine();
		_builder_1.append("]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(27, 0);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void guard_self() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final EReference _event_Guard = AFowlerdslDefaultModelTest.statemachineFactory.getStatemachinePackage()
				.getEvent_Guard();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(null, event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("guard")), _event_Guard);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event1[");
		_builder_1.newLine();
		_builder_1.append("]");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(27, 0);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertNull(preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCode_singleLine() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("2");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final Set<String> _emptySet = CollectionLiterals.<String> emptySet();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false, _emptySet);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1  \t  \t  \t2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1  \t  \t  \t2", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(30, 16);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameGuard_nameGuard_singleLine() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 \t\t[");
		_builder.newLine();
		_builder.append("1\t\t  \t\t..");
		_builder.newLine();
		_builder.append("2               ]");
		_builder.newLine();
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[");
		_builder.newLine();
		_builder.append("\t    ");
		_builder.append("42");
		_builder.newLine();
		_builder.append("\t    \t");
		_builder.append("] event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 \t\t[");
		_builder_1.newLine();
		_builder_1.append("1\t\t  \t\t..");
		_builder_1.newLine();
		_builder_1.append("2               ]");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("event1  \t[  \t    42  \t    \t] event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1  \t[  \t    42  \t    \t]", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(53, 28);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameCode_multiLine() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("2");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("3");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final Set<String> _emptySet = CollectionLiterals.<String> emptySet();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptySet);
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("3");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1\r\n\t\r\n\t\r\n\t2", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(30, 16);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void eventNameGuard_nameGuard_multiLine() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 \t\t[");
		_builder.newLine();
		_builder.append("1\t\t  \t\t..");
		_builder.newLine();
		_builder.append("2               ]");
		_builder.newLine();
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[");
		_builder.newLine();
		_builder.append("\t    ");
		_builder.append("42");
		_builder.newLine();
		_builder.append("\t    \t");
		_builder.append("] event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Event event = model.getEvents().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("name", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 \t\t[");
		_builder_1.newLine();
		_builder_1.append("1\t\t  \t\t..");
		_builder_1.newLine();
		_builder_1.append("2               ]");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[");
		_builder_1.newLine();
		_builder_1.append("\t    ");
		_builder_1.append("42");
		_builder_1.newLine();
		_builder_1.append("\t    \t");
		_builder_1.append("] event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1\r\n\t[\r\n\t    42\r\n\t    \t]", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(53, 28);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void transitionOnlyEvent_eventGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 => state1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 => state2");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2 => state2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state1");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final State state = model.getStates().get(0);
		final Transition transition = state.getTransitions().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(transition, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("event", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 => state1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 => state2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2 => state2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state1");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(78, 6);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(transition, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void transitionEventGuard_eventGuard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("events");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("const0 23");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state0");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event0 => state1");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event1 [const0] => state2");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("event2 => state2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state1");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("state state2");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final State state = model.getStates().get(0);
		final Transition transition = state.getTransitions().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(transition, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("event", "guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("events");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("const0 23");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state0");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event0 => state1");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("event1 [const0] => state2");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("event2 => state2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state1");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("state state2");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("event1 [const0]", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(108, 15);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(transition, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void commandNameCode_nameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("commands");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd0 12");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd1 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[e.. pi] cmd2 234");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("e 271");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("pi 314");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Command cmd = model.getCommands().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("code", "name")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("commands");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("cmd0 12");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("cmd1 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[e.. pi] cmd2 234");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("e 271");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("pi 314");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("cmd1 123", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(23, 8);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(cmd, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void commandGuardNameCode_nameCode() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("commands");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd0 12");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[123] cmd1 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[e.. pi] cmd2 234");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("e 271");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("pi 314");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Command cmd = model.getCommands().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("code", "name")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("commands");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("cmd0 12");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[123] ");
		_builder_1.newLine();
		_builder_1.append("cmd1 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[e.. pi] cmd2 234");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("e 271");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("pi 314");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("cmd1 123", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(29, 8);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(cmd, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void commandGuardNameCode_guardName() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("commands");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd0 12");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[123] cmd1 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[e.. pi] cmd2 234");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("e 271");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("pi 314");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Command cmd = model.getCommands().get(2);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("guard", "name")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("commands");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("cmd0 12");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[123] cmd1 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.newLine();
		_builder_1.append("[e.. pi] cmd2 234");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("e 271");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("pi 314");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("[e.. pi] cmd2", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(40, 13);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(cmd, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
	
	@Test
	public void commandNameCode_guard() {
		final StringConcatenation _builder = new StringConcatenation();
		_builder.append("commands");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd0 12");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("cmd1 123");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("[e.. pi] cmd2 234");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		_builder.newLine();
		_builder.append("constants");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("e 271");
		_builder.newLine();
		_builder.append("\t");
		_builder.append("pi 314");
		_builder.newLine();
		_builder.append("end");
		_builder.newLine();
		final Statemachine model = this.parseIntoResource(_builder.toString());
		final Command cmd = model.getCommands().get(1);
		final Injector _injector = getInjector();
		final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true,
				Collections.<String> unmodifiableSet(CollectionLiterals.<String> newHashSet("guard")));
		final StringConcatenation _builder_1 = new StringConcatenation();
		_builder_1.append("commands");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("cmd0 12");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[");
		_builder_1.newLine();
		_builder_1.append("]cmd1 123");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("[e.. pi] cmd2 234");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		_builder_1.newLine();
		_builder_1.append("constants");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("e 271");
		_builder_1.newLine();
		_builder_1.append("\t");
		_builder_1.append("pi 314");
		_builder_1.newLine();
		_builder_1.append("end");
		_builder_1.newLine();
		Assert.assertEquals(_builder_1.toString(), preparer.getText());
		final TextRegion textRegion = preparer.getTextRegion();
		final String _text = preparer.getText();
		final int _offset = textRegion.getOffset();
		final int _offset_1 = textRegion.getOffset();
		final int _length = textRegion.getLength();
		final int _plus = (_offset_1 + _length);
		Assert.assertEquals("", _text.substring(_offset, _plus));
		final TextRegion _textRegion = new TextRegion(24, 0);
		Assert.assertEquals(_textRegion, preparer.getTextRegion());
		Assert.assertSame(cmd, preparer.getSemanticElementLocation().resolve(model.eResource()));
	}
}
