/**
 * generated by Xtext 2.22.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.refLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>References3</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.altran.general.integration.xtextsirius.test.reflang.refLang.References3#getReferences3 <em>References3</em>}</li>
 * </ul>
 *
 * @see com.altran.general.integration.xtextsirius.test.reflang.refLang.RefLangPackage#getReferences3()
 * @model
 * @generated
 */
public interface References3 extends EObject
{
  /**
   * Returns the value of the '<em><b>References3</b></em>' containment reference list.
   * The list contents are of type {@link com.altran.general.integration.xtextsirius.test.reflang.refLang.Reference3}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>References3</em>' containment reference list.
   * @see com.altran.general.integration.xtextsirius.test.reflang.refLang.RefLangPackage#getReferences3_References3()
   * @model containment="true"
   * @generated
   */
  EList<Reference3> getReferences3();

} // References3
