/**
 * generated by Xtext 2.14.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.refLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.altran.general.integration.xtextsirius.test.reflang.refLang.SubContainer#getName <em>Name</em>}</li>
 *   <li>{@link com.altran.general.integration.xtextsirius.test.reflang.refLang.SubContainer#getSubContents <em>Sub Contents</em>}</li>
 * </ul>
 *
 * @see com.altran.general.integration.xtextsirius.test.reflang.refLang.RefLangPackage#getSubContainer()
 * @model
 * @generated
 */
public interface SubContainer extends IContainerContent, References, References2, References3
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.altran.general.integration.xtextsirius.test.reflang.refLang.RefLangPackage#getSubContainer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.altran.general.integration.xtextsirius.test.reflang.refLang.SubContainer#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sub Contents</b></em>' containment reference list.
   * The list contents are of type {@link com.altran.general.integration.xtextsirius.test.reflang.refLang.IContainerContent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Contents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Contents</em>' containment reference list.
   * @see com.altran.general.integration.xtextsirius.test.reflang.refLang.RefLangPackage#getSubContainer_SubContents()
   * @model containment="true"
   * @generated
   */
  EList<IContainerContent> getSubContents();

} // SubContainer
