package com.altran.general.integration.xtextsirius.test.util.modelregioneditorpreparer;

import com.altran.general.integration.xtextsirius.test.AFowlerdslDefaultModelTest;
import com.altran.general.integration.xtextsirius.test.util.modelregioneditorpreparer.AModelRegionEditorPreparer;
import com.altran.general.integration.xtextsirius.util.ModelRegionEditorPreparer;
import com.altran.general.integration.xtextsirius.util.SemanticElementLocation;
import com.google.inject.Injector;
import java.util.Collections;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Command;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Event;
import org.eclipse.xtext.example.fowlerdsl.statemachine.State;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Statemachine;
import org.eclipse.xtext.example.fowlerdsl.statemachine.StatemachinePackage;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Transition;
import org.eclipse.xtext.util.TextRegion;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.junit.Assert;
import org.junit.Test;

@SuppressWarnings("all")
public class TestApiMultiEntries extends AModelRegionEditorPreparer {
  @Test
  public void eventOnlyName() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(20, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 2", _substring);
    TextRegion _textRegion = new TextRegion(22, 8);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCodeGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 1 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 2 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 1 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 2 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 2 [42]", _substring);
    TextRegion _textRegion = new TextRegion(30, 13);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventOnlyName_name() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(20, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCode_name() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(24, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCode_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 234", _substring);
    TextRegion _textRegion = new TextRegion(24, 10);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameGuard_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(28, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameGuard_nameGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 [42]", _substring);
    TextRegion _textRegion = new TextRegion(28, 11);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCodeGuard_nameGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 234 [42]", _substring);
    TextRegion _textRegion = new TextRegion(32, 15);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventName_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(20, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventName_nameCodeGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.code", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(20, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventName_guard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1[");
    _builder_1.newLine();
    _builder_1.append("]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("", _substring);
    TextRegion _textRegion = new TextRegion(27, 0);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void guard_self() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    StatemachinePackage _statemachinePackage = AFowlerdslDefaultModelTest.statemachineFactory.getStatemachinePackage();
    EReference _event_Guard = _statemachinePackage.getEvent_Guard();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(null, event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.guard")), _event_Guard);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1[");
    _builder_1.newLine();
    _builder_1.append("]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("", _substring);
    TextRegion _textRegion = new TextRegion(27, 0);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertNull(_resolve);
  }
  
  @Test
  public void eventNameCode_singleLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1  \t  \t  \t2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1  \t  \t  \t2", _substring);
    TextRegion _textRegion = new TextRegion(30, 16);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameGuard_nameGuard_singleLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 \t\t[");
    _builder.newLine();
    _builder.append("1\t\t  \t\t..");
    _builder.newLine();
    _builder.append("2               ]");
    _builder.newLine();
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("42");
    _builder.newLine();
    _builder.append("\t    \t");
    _builder.append("] event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 \t\t[");
    _builder_1.newLine();
    _builder_1.append("1\t\t  \t\t..");
    _builder_1.newLine();
    _builder_1.append("2               ]");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("event1  \t[  \t    42  \t    \t] event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1  \t[  \t    42  \t    \t]", _substring);
    TextRegion _textRegion = new TextRegion(53, 28);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameCode_multiLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1\r\n\t\r\n\t\r\n\t2", _substring);
    TextRegion _textRegion = new TextRegion(30, 16);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void eventNameGuard_nameGuard_multiLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 \t\t[");
    _builder.newLine();
    _builder.append("1\t\t  \t\t..");
    _builder.newLine();
    _builder.append("2               ]");
    _builder.newLine();
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("42");
    _builder.newLine();
    _builder.append("\t    \t");
    _builder.append("] event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Event> _events = model.getEvents();
    final Event event = _events.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.name", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 \t\t[");
    _builder_1.newLine();
    _builder_1.append("1\t\t  \t\t..");
    _builder_1.newLine();
    _builder_1.append("2               ]");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("42");
    _builder_1.newLine();
    _builder_1.append("\t    \t");
    _builder_1.append("] event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1\r\n\t[\r\n\t    42\r\n\t    \t]", _substring);
    TextRegion _textRegion = new TextRegion(53, 28);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(event, _resolve);
  }
  
  @Test
  public void transitionOnlyEvent_eventGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 => state1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 => state2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 => state2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state1");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<State> _states = model.getStates();
    final State state = _states.get(0);
    EList<Transition> _transitions = state.getTransitions();
    final Transition transition = _transitions.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(transition, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.event", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 => state1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 => state2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 => state2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state1");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1", _substring);
    TextRegion _textRegion = new TextRegion(78, 6);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(transition, _resolve);
  }
  
  @Test
  public void transitionEventGuard_eventGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("const0 23");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 => state1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 [const0] => state2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 => state2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state1");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("state state2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<State> _states = model.getStates();
    final State state = _states.get(0);
    EList<Transition> _transitions = state.getTransitions();
    final Transition transition = _transitions.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(transition, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.event", "Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("const0 23");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 => state1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 [const0] => state2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 => state2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state1");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("state state2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("event1 [const0]", _substring);
    TextRegion _textRegion = new TextRegion(108, 15);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(transition, _resolve);
  }
  
  @Test
  public void commandNameCode_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("commands");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd0 12");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd1 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[e.. pi] cmd2 234");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("e 271");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Command> _commands = model.getCommands();
    final Command cmd = _commands.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.code", "Event.name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("commands");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("cmd0 12");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("cmd1 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[e.. pi] cmd2 234");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("e 271");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("cmd1 123", _substring);
    TextRegion _textRegion = new TextRegion(23, 8);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(cmd, _resolve);
  }
  
  @Test
  public void commandGuardNameCode_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("commands");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd0 12");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[123] cmd1 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[e.. pi] cmd2 234");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("e 271");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Command> _commands = model.getCommands();
    final Command cmd = _commands.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.code", "Event.name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("commands");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("cmd0 12");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[123] ");
    _builder_1.newLine();
    _builder_1.append("cmd1 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[e.. pi] cmd2 234");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("e 271");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("cmd1 123", _substring);
    TextRegion _textRegion = new TextRegion(29, 8);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(cmd, _resolve);
  }
  
  @Test
  public void commandGuardNameCode_guardName() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("commands");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd0 12");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[123] cmd1 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[e.. pi] cmd2 234");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("e 271");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Command> _commands = model.getCommands();
    final Command cmd = _commands.get(2);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.guard", "Event.name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("commands");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("cmd0 12");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[123] cmd1 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("[e.. pi] cmd2 234");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("e 271");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("[e.. pi] cmd2", _substring);
    TextRegion _textRegion = new TextRegion(40, 13);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(cmd, _resolve);
  }
  
  @Test
  public void commandNameCode_guard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("commands");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd0 12");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("cmd1 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[e.. pi] cmd2 234");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("e 271");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    EList<Command> _commands = model.getCommands();
    final Command cmd = _commands.get(1);
    Injector _injector = this.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(cmd, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("Event.guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("commands");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("cmd0 12");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[");
    _builder_1.newLine();
    _builder_1.append("]cmd1 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[e.. pi] cmd2 234");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("e 271");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    String _string = _builder_1.toString();
    String _text = preparer.getText();
    Assert.assertEquals(_string, _text);
    final TextRegion textRegion = preparer.getTextRegion();
    String _text_1 = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    String _substring = _text_1.substring(_offset, _plus);
    Assert.assertEquals("", _substring);
    TextRegion _textRegion = new TextRegion(24, 0);
    TextRegion _textRegion_1 = preparer.getTextRegion();
    Assert.assertEquals(_textRegion, _textRegion_1);
    SemanticElementLocation _semanticElementLocation = preparer.getSemanticElementLocation();
    Resource _eResource = model.eResource();
    EObject _resolve = _semanticElementLocation.resolve(_eResource);
    Assert.assertSame(cmd, _resolve);
  }
}
