package com.altran.general.integration.xtextsirius.test.util.modelregioneditorpreparer;

import com.altran.general.integration.xtextsirius.test.AFowlerdslDefaultModelTest;
import com.altran.general.integration.xtextsirius.test.AFowlerdslTest;
import com.altran.general.integration.xtextsirius.test.util.modelregioneditorpreparer.AModelRegionEditorPreparer;
import com.altran.general.integration.xtextsirius.util.ModelRegionEditorPreparer;
import com.google.inject.Injector;
import java.util.Collections;
import java.util.List;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Event;
import org.eclipse.xtext.example.fowlerdsl.statemachine.Statemachine;
import org.eclipse.xtext.util.TextRegion;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.junit.Assert;
import org.junit.Test;

@SuppressWarnings("all")
public class TestApiMultiEntries extends AModelRegionEditorPreparer {
  @Test
  public void eventOnlyName() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(20, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1 2", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(22, 8);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCodeGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 1 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 2 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("constants");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("pi 314");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 1 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 2 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("constants");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("pi 314");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1 2 [42]", 
      _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(30, 13);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventOnlyName_name() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(20, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCode_name() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(24, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCode_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1 234", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(24, 10);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameGuard_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(28, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameGuard_nameGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1 [42]", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(28, 11);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCodeGuard_nameGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 123 [pi..1]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1 234 [42]");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event3 345");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 123 [pi..1]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1 234 [42]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event3 345");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1 234 [42]", 
      _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(32, 15);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventName_nameCode() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "code")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(20, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventName_nameCodeGuard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "code", "guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(20, 6);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventName_guard() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1[");
    _builder_1.newLine();
    _builder_1.append("]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(27, 0);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void guard_self() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    EReference _event_Guard = AFowlerdslDefaultModelTest.statemachineFactory.getStatemachinePackage().getEvent_Guard();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(null, event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("guard")), _event_Guard);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event1[");
    _builder_1.newLine();
    _builder_1.append("]");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(27, 0);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertNull(preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCode_singleLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1  \t  \t  \t2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1  \t  \t  \t2", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(30, 16);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameGuard_nameGuard_singleLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 \t\t[");
    _builder.newLine();
    _builder.append("1\t\t  \t\t..");
    _builder.newLine();
    _builder.append("2               ]");
    _builder.newLine();
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("42");
    _builder.newLine();
    _builder.append("\t    \t");
    _builder.append("] event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, false, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 \t\t[");
    _builder_1.newLine();
    _builder_1.append("1\t\t  \t\t..");
    _builder_1.newLine();
    _builder_1.append("2               ]");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("event1  \t[  \t    42  \t    \t] event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1  \t[  \t    42  \t    \t]", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(53, 28);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameCode_multiLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("2");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event2");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("3");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    List<String> _emptyList = CollectionLiterals.<String>emptyList();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, _emptyList);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event2");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("3");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1\r\n\t\r\n\t\r\n\t2", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(30, 16);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
  
  @Test
  public void eventNameGuard_nameGuard_multiLine() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("events");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("event0 \t\t[");
    _builder.newLine();
    _builder.append("1\t\t  \t\t..");
    _builder.newLine();
    _builder.append("2               ]");
    _builder.newLine();
    _builder.append("event1");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("[");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("42");
    _builder.newLine();
    _builder.append("\t    \t");
    _builder.append("] event2");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    final Statemachine model = this.parseIntoResource(_builder.toString());
    final Event event = model.getEvents().get(1);
    Injector _injector = AFowlerdslTest.getInjector();
    final ModelRegionEditorPreparer preparer = new ModelRegionEditorPreparer(event, _injector, true, Collections.<String>unmodifiableList(CollectionLiterals.<String>newArrayList("name", "guard")));
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("events");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("event0 \t\t[");
    _builder_1.newLine();
    _builder_1.append("1\t\t  \t\t..");
    _builder_1.newLine();
    _builder_1.append("2               ]");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("event1");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("[");
    _builder_1.newLine();
    _builder_1.append("\t    ");
    _builder_1.append("42");
    _builder_1.newLine();
    _builder_1.append("\t    \t");
    _builder_1.append("] event2");
    _builder_1.newLine();
    _builder_1.append("end");
    _builder_1.newLine();
    Assert.assertEquals(_builder_1.toString(), preparer.getText());
    final TextRegion textRegion = preparer.getTextRegion();
    String _text = preparer.getText();
    int _offset = textRegion.getOffset();
    int _offset_1 = textRegion.getOffset();
    int _length = textRegion.getLength();
    int _plus = (_offset_1 + _length);
    Assert.assertEquals("event1\r\n\t[\r\n\t    42\r\n\t    \t]", _text.substring(_offset, _plus));
    TextRegion _textRegion = new TextRegion(53, 28);
    Assert.assertEquals(_textRegion, preparer.getTextRegion());
    Assert.assertSame(event, preparer.getSemanticElementLocation().resolve(model.eResource()));
  }
}
