/*
 * generated by Xtext 2.22.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.edit.scoping;

import com.altran.general.integration.xtextsirius.test.reflang.scoping.RefLangScopeProvider;

public abstract class AbstractRefLangEditScopeProvider extends RefLangScopeProvider {
}
