/**
 * generated by Xtext 2.14.0
 */
package com.altran.general.integration.xtextsirius.test.reflang.edit.ui.quickfix;

import com.altran.general.integration.xtextsirius.test.reflang.ui.quickfix.RefLangQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class RefLangEditQuickfixProvider extends RefLangQuickfixProvider {
}
